const text = d3.text('data/tomtittot.txt').then(function(data) {
    console.log(data);
});

var story_files = {
    "TOM TIT TOT": "tomtittom",
    "THE THREE SILLIES": "thethreesillies",
    "THE ROSE-TREE": "therose-tree",
    "THE OLD WOMAN AND HER PIG": "theoldwomanandherpig",
    "HOW JACK WENT TO SEEK HIS FORTUNE": "howjackwenttoseekhisfortune",
    "MR. VINEGAR": "mrvinegar",
    "NIX NOUGHT NOTHING": "nixnoughtnothing",
    "JACK HANNAFORD": "jackhannaford",
    "BINNORIE": "binnorie",
    "MOUSE AND MOUSER": "mouseandmouser",
    "CAP O' RUSHES": "caporushes",
    "TEENY-TINY": "teeny-tiny",
    "JACK AND THE BEANSTALK": "jackandthebeanstalk",
    "THE STORY OF THE THREE LITTLE PIGS": "thestoryofthethreelittlepigs",
    "THE MASTER AND HIS PUPIL": "themasterandhispupil",
    "TITTY MOUSE AND TATTY MOUSE": "tittymouseandtattymouse",
    "JACK AND HIS GOLDEN SNUFF-BOX": "jackandhisgoldensnuff-box",
    "THE STORY OF THE THREE BEARS": "thestoryofthethreebears",
    "JACK THE GIANT-KILLER": "jackthegiant-killer",
    "HENNY-PENNY": "henny-penny",
    "CHILDE ROWLAND": "childerowland",
    "MOLLY WHUPPIE": "mollywhuppie",
    "THE RED ETTIN" : "theredettin",
    "THE GOLDEN ARM": "thegoldenarm",
    "THE HISTORY OF TOM THUMB": "thehistoryoftomthumb",
    "MR. FOX": "mrfox",
    "LAZY JACK": "lazyjack",
    "JOHNNY-CAKE": "johnny-cake",
    "EARL MAR'S DAUGHTER": "earlmarsdaughter",
    "MR. MIACCA": "mrmiacca",
    "WHITTINGTON AND HIS CAT": "whittingtonandhiscat",
    "THE STRANGE VISITOR": "thestrangevisitor",
    "THE LAIDLY WORM OF SPINDLESTON HEUGH": "thelaidlywormofspindlestonheugh",
    "THE CAT AND THE MOUSE": "thecatandthemouse",
    "THE FISH AND THE RING": "thefishandthering",
    "THE MAGPIE'S NEST": "themagpiesnest",
    "KATE CRACKERNUTS": "katecrackernuts",
    "THE CAULD LAD OF HILTON": "thecauldladofhilton",
    "THE ASS, THE TABLE, AND THE STICK": "theassthetableandthestick",
    "FAIRY OINTMENT": "fairyointment",
    "THE WELL OF THE WORLD'S END": "thewelloftheworldsend",
    "MASTER OF ALL MASTERS": "masterofallmasters",
    "THE THREE HEADS OF THE WELL": "thethreeheadsofthewell"
}